create table games (guest_team_points integer not null, home_team_points integer not null, is_played boolean not null, round integer not null, guest_team_id bigint, home_team_id bigint, id bigint generated by default as identity, primary key (id));
create table player_stats (player_points integer not null, game_id bigint not null, player_id bigint not null, primary key (game_id, player_id));
create table players (birth_date date, jersey_number integer not null, id bigint generated by default as identity, team_id bigint, first_name varchar(255), image_path varchar(255), last_name varchar(255), primary key (id));
create table table_fields (losses integer not null, plus_minus integer not null, points integer not null, wins integer not null, id bigint generated by default as identity, team_id bigint, primary key (id));
create table teams (id bigint generated by default as identity, hall varchar(255), image_path varchar(255), logo_path varchar(255), name varchar(255), primary key (id));
